/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/taylor/src/ros/catkin_ws/src/pick/srv/Button.srv
 *
 */


#ifndef PICK_MESSAGE_BUTTON_H
#define PICK_MESSAGE_BUTTON_H

#include <ros/service_traits.h>


#include <pick/ButtonRequest.h>
#include <pick/ButtonResponse.h>


namespace pick
{

struct Button
{

typedef ButtonRequest Request;
typedef ButtonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Button
} // namespace pick


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pick::Button > {
  static const char* value()
  {
    return "fce55d8d6e1bc1923599409813fddc68";
  }

  static const char* value(const ::pick::Button&) { return value(); }
};

template<>
struct DataType< ::pick::Button > {
  static const char* value()
  {
    return "pick/Button";
  }

  static const char* value(const ::pick::Button&) { return value(); }
};


// service_traits::MD5Sum< ::pick::ButtonRequest> should match 
// service_traits::MD5Sum< ::pick::Button > 
template<>
struct MD5Sum< ::pick::ButtonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pick::Button >::value();
  }
  static const char* value(const ::pick::ButtonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick::ButtonRequest> should match 
// service_traits::DataType< ::pick::Button > 
template<>
struct DataType< ::pick::ButtonRequest>
{
  static const char* value()
  {
    return DataType< ::pick::Button >::value();
  }
  static const char* value(const ::pick::ButtonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pick::ButtonResponse> should match 
// service_traits::MD5Sum< ::pick::Button > 
template<>
struct MD5Sum< ::pick::ButtonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pick::Button >::value();
  }
  static const char* value(const ::pick::ButtonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick::ButtonResponse> should match 
// service_traits::DataType< ::pick::Button > 
template<>
struct DataType< ::pick::ButtonResponse>
{
  static const char* value()
  {
    return DataType< ::pick::Button >::value();
  }
  static const char* value(const ::pick::ButtonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICK_MESSAGE_BUTTON_H
